# Generated by Django 5.2.15 on 2026-06-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('symbol', models.CharField(blank=True, help_text='Symbole/ticker, ex. XAU', max_length=16)),
                ('category', models.CharField(choices=[('precious', 'Métal précieux'), ('base', 'Métal de base / industriel'), ('battery', 'Métal pour batteries'), ('other', 'Autre')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('price_unit', models.CharField(default='USD/t', help_text='Unité canonique du prix, ex. USD/t, USD/ozt', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('price_provider', models.CharField(default='commodities_api', max_length=32)),
                ('price_symbol', models.CharField(blank=True, help_text='Symbole côté fournisseur, ex. LCO, ALU, XAU', max_length=24)),
            ],
            options={
                'verbose_name': 'matière première',
                'verbose_name_plural': 'matières premières',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('iso2', models.CharField(blank=True, max_length=2)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'pays',
                'verbose_name_plural': 'pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('type', models.CharField(choices=[('war', 'Conflit / Guerre'), ('policy', 'Politique / Régulation'), ('disaster', 'Catastrophe'), ('economic', 'Économique'), ('other', 'Autre')], default='other', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('prices', 'Cours (quotidien)'), ('enrich', 'Enrichissement (mensuel)'), ('full', 'Mise à jour complète')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('error', 'Erreur')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'import',
                'verbose_name_plural': 'imports',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('nace_code', models.CharField(blank=True, help_text='Code NACE-2 (RMIS)', max_length=16)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'secteur',
                'verbose_name_plural': 'secteurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('reserves_t', models.DecimalField(decimal_places=2, help_text='Réserves en tonnes', max_digits=22)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='commodities.commodity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='commodities.country')),
            ],
            options={
                'verbose_name': 'réserve',
                'verbose_name_plural': 'réserves',
                'ordering': ['-year', '-reserves_t'],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'country', 'year'), name='uniq_reserve_commodity_country_year')],
            },
        ),
        migrations.CreateModel(
            name='CommodityProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('production_t', models.DecimalField(decimal_places=2, help_text='Production annuelle en tonnes', max_digits=22)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='commodities.commodity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='commodities.country')),
            ],
            options={
                'verbose_name': 'production',
                'verbose_name_plural': 'productions',
                'ordering': ['-year', '-production_t'],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'country', 'year'), name='uniq_production_commodity_country_year')],
            },
        ),
        migrations.CreateModel(
            name='EventImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('direction', models.CharField(choices=[('up', 'Hausse'), ('down', 'Baisse'), ('neutral', 'Neutre')], default='neutral', max_length=8)),
                ('magnitude', models.DecimalField(blank=True, decimal_places=2, help_text='Variation estimée en %', max_digits=7, null=True)),
                ('description', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='commodities.commodity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='commodities.event')),
            ],
            options={
                'verbose_name': 'impact (événement)',
                'verbose_name_plural': 'impacts (événements)',
                'ordering': ['-event__start_date'],
                'constraints': [models.UniqueConstraint(fields=('event', 'commodity'), name='uniq_impact_event_commodity')],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField()),
                ('price_usd', models.DecimalField(decimal_places=4, max_digits=16)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='commodities.commodity')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'date', 'source'), name='uniq_quote_commodity_date_source')],
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(blank=True, help_text='Rôle de la matière dans le produit', max_length=200)),
                ('needs_review', models.BooleanField(default=False)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='commodities.commodity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='commodities.product')),
            ],
            options={
                'verbose_name': 'composition (produit)',
                'verbose_name_plural': 'compositions (produits)',
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'product'), name='uniq_composition_commodity_product')],
            },
        ),
        migrations.CreateModel(
            name='CommodityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('share_percent', models.DecimalField(blank=True, decimal_places=2, help_text="Part d'usage en %", max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='commodities.commodity')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='commodities.sector')),
            ],
            options={
                'verbose_name': 'usage (secteur)',
                'verbose_name_plural': 'usages (secteurs)',
                'ordering': ['-share_percent'],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'sector'), name='uniq_usage_commodity_sector')],
            },
        ),
    ]
