# Generated by Django 5.2.15 on 2026-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='category',
            field=models.CharField(choices=[('energy', 'Énergie'), ('precious', 'Métal précieux'), ('base', 'Métal de base / industriel'), ('battery', 'Métal pour batteries'), ('agricultural', 'Agricole'), ('fertilizer', 'Engrais'), ('other', 'Autre')], default='other', max_length=16),
        ),
    ]
