# Generated by Django 5.2.15 on 2026-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_alter_commodity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price_symbol',
            field=models.CharField(blank=True, help_text='Symbole/label côté fournisseur (ex. LCO, Crude oil, Brent)', max_length=64),
        ),
    ]
