# Generated by Django 5.2.15 on 2026-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_alter_commodity_price_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityproduction',
            name='unit',
            field=models.CharField(default='t', help_text='Unité (t, TWh…)', max_length=8),
        ),
        migrations.AlterField(
            model_name='commodityproduction',
            name='production_t',
            field=models.DecimalField(decimal_places=2, help_text='Valeur de production annuelle', max_digits=22),
        ),
    ]
