# Generated by Django 5.2.15 on 2026-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0004_commodityproduction_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='api_symbol',
            field=models.CharField(blank=True, help_text='Ticker Commodities-API pour la MAJ quotidienne (ex. XAU, BRENTOIL). Vide ⇒ pas de cours quotidien, repli sur le fournisseur historique.', max_length=32),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price_provider',
            field=models.CharField(default='commodities_api', help_text='Fournisseur historique / de repli (ex. worldbank, usgs_price)', max_length=32),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price_symbol',
            field=models.CharField(blank=True, help_text="Label côté fournisseur historique (ex. 'Gold', 'Crude oil, Brent')", max_length=64),
        ),
    ]
