# Generated by Django 5.2.15 on 2026-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0005_commodity_api_symbol_alter_commodity_price_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityproduction',
            name='note',
            field=models.CharField(blank=True, help_text="Base de la mesure (ex. Production minière, Production d'énergie)", max_length=64),
        ),
    ]
