# Generated by Django 5.2.15 on 2026-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0006_commodityproduction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityreserve',
            name='unit',
            field=models.CharField(default='t', help_text='Unité (t, m³…)', max_length=8),
        ),
        migrations.AlterField(
            model_name='commodityreserve',
            name='reserves_t',
            field=models.DecimalField(decimal_places=2, help_text='Quantité de réserves', max_digits=22),
        ),
    ]
