# Generated by Django 5.2.15 on 2026-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0008_relabel_rice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
