# Generated by Django 5.2.15 on 2026-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0009_alter_event_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('war', 'Conflit / Guerre'), ('policy', 'Politique / Régulation'), ('disaster', 'Catastrophe'), ('economic', 'Marché'), ('other', 'Autre')], default='other', max_length=16),
        ),
    ]
