# Generated by Django 5.2.15 on 2026-06-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ticker, ex. NDDUWI', max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_class', models.CharField(choices=[('equity', 'Actions'), ('bond', 'Obligations'), ('high_yield', 'High yield'), ('hedge_fund', 'Hedge funds'), ('cta', 'CTA / Managed futures'), ('cash', 'Monétaire'), ('cpi', 'Inflation (IPC)'), ('fx', 'Change')], max_length=16)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar US')], default='USD', max_length=3)),
                ('source', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'actif financier',
                'verbose_name_plural': 'actifs financiers',
                'ordering': ['asset_class', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='markets.marketasset')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['asset', 'date'], name='markets_ass_asset_i_99dbba_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='uniq_assetprice_asset_date')],
            },
        ),
    ]
