# Generated by Django 5.2.15 on 2026-06-22 14:04

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0011_alter_event_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('base_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar US')], default='EUR', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('fee_percent', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=6)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portefeuille',
                'verbose_name_plural': 'portefeuilles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('deposit', 'Dépôt'), ('withdraw', 'Retrait'), ('buy', 'Achat'), ('sell', 'Vente')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='commodities.commodity')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['date', 'id'],
            },
        ),
    ]
